name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
      - name: Sync dependencies
        run: uv sync --dev
      - name: Lint
        run: uv run -s lint
      - name: Type check
        run: uv run -s typecheck
      - name: Tests
        run: uv run -s test
